#Users
VALID_USERNAME = 'user1'
VALID_EMAIL = 'user1@email.com'
VALID_PASSWORD = 'user1p@ss'

#Page Titles
HOME_PAGE_TITLE = 'Login'
LANDING_PAGE_TITLE = 'Home'

#Browser dimensions
MIN_MOBILE_WIDTH = '800'
MAX_MOBILE_WIDTH = '800'
MIN_MOBILE_HEIGHT = '0'
MAX_MOBILE_HEIGHT = '767'
MIN_TABLET_WIDTH = '800'
MAX_TABLET_WIDTH = '800'
MIN_TABLET_HEIGHT = '768'
MAX_TABLET_HEIGHT = '991'
MIN_DESKTOP_WIDTH = '800'
MAX_DESKTOP_WIDTH = '1280'
MIN_DESKTOP_HEIGHT = '992'
MAX_DESKTOP_HEIGHT = '1024'
